### ISSUE TITLE
Updating GOG shape

### ISSUE THREAD

**Issue by raghulsekar** [USNavalResearchLaboratory/simdissdk#100]
Is there any example to update GOG shapes using callback , i tried using example_customrenderingtest but the output was not as expected. I just need a shape attached to a property which updates for each second.

**Comment by emminizer** [comment]
Examples/GOGAttachments (`example_gogattachments`) shows the GOG attached to a platform that cycles through with a callback activated by a hot key. The Custom Rendering Test does not have any GOG, and instead is focused on custom render entities.

**Comment by raghulsekar** [comment]
will i be able to update x,y of the shape?

**Comment by emminizer** [comment]
If you change the string that controls the GOG generation sure. If you're looking to move GOG manually using some sort of transform, no; you can attach it to a platform as shown in the example. If you want more detailed control of individual shapes in the scene look at the underlying Features interface in osgEarth on which GOG is built upon.

**Comment by raghulsekar** [comment]
Sure will work on it
