### ISSUE TITLE
PlatformNode is attached to Mapnode?

### ISSUE THREAD

**Issue by raghulsekar** [USNavalResearchLaboratory/simdissdk#103]
what is the hierarchy of attaching PlatformNode (the one that contains the icon/model) to the earth node) , i would like to know if the model nodes are getting added to map node or not?

**Comment by emminizer** [comment]
Please take a look at any of the examples that use Platforms in the data store to see the hierarchy. Models are under platform nodes, which are generally under a group under ScenarioManager, under drapeable scene objects under the sky node. See the following screenshot from an internal tool in the SIMDIS application:

![image](https://github.com/USNavalResearchLaboratory/simdissdk/assets/3845830/c5f9f333-69a0-45d7-9a9f-585b549342ec)

**Comment by raghulsekar** [comment]
Thanks!
