### ISSUE TITLE
Ground Clipping

### ISSUE THREAD

**Issue by faculaganymede** [USNavalResearchLaboratory/simdissdk#110]
When the camera is at low elevation, part of the ground gets clipped and shows up black (as shown in the image below).  I believe this has to do with the view frustum clipping.  Is there a setting that would adjust the view frustum when the camera is at low elevation and show the ground continuously?

![image](https://github.com/USNavalResearchLaboratory/simdissdk/assets/123752354/2da1932d-3605-4569-b688-d68a33728966)

**Comment by emminizer** [comment]
Take a look at simVis/View.cpp's SetNearFarCallback. Most of then near/far clip plane management is done in OSG. See also the ClampNearPlaneCallback in simVis/ViewManagerLogDbAdapter, which helps with the Logarithmic Depth Buffer provided by osgEarth. Logarithmic Depth Buffer (LDB) helps tremendously in the overwhelmingly common cases, but it breaks somewhat quickly with surfaces that intersect the near plane. You can opt to disable LDB which can give you more traditional access to OSG's near/far clipping plane values.
