### ISSUE TITLE
glTF output comes tilted

### ISSUE THREAD

**Issue by raghulsekar** [USNavalResearchLaboratory/simdissdk#114]
My workflow here is to get an output from blender in glTF format, with (with +y up disabled), and load it in SIMDIS. The problem that I am facing is the model loads tilted on 2 axes. I want to know what is the reason behind this, since both platforms are built with OpenGL.
![image (5)](https://github.com/user-attachments/assets/ad6ef6e6-03d5-4ec3-83d0-455c92e47abd)
![image (4)](https://github.com/user-attachments/assets/a80f5cb2-8c82-4bb1-8ac1-df1bbd32ae58)

also the set_iconroticons() does not reflect any change to my model.

**Comment by emminizer** [comment]
SIMDIS (and SIMDIS SDK) expects a certain orientation for models for the X/Y/Z orientation. You can see the model in the ModelViewer application that ships with SIMDIS if you like to see how the third party libraries load the GLTF. I believe this is imported using osgEarth's GLTF driver, which uses tinygltf.

You can adjust the orientation of any model associated with a given platform by changing the `PlatformPrefs::orientationOffset`. This is intended to apply an offset to orientation values, in body angles.

`PlatformPrefs::rotateIcons` is for 2D icons (PNG files) and not 3D models.

**Comment by raghulsekar** [comment]
Thanks a lot
