### ISSUE TITLE
Stage seperation of Model's

### ISSUE THREAD

**Issue by raghulsekar** [USNavalResearchLaboratory/simdissdk#116]
@emminizer is it possible to do rocket stage separation using the existing PlatformNode, assuming the model loaded has separate named nodes for each stage. Any example's that i can refer?

**Comment by emminizer** [comment]
We typically do this in our own displays by swapping out the model.

Take a look at ExampleArticulatedModel.cpp for a similar approach that uses articulations on named nodes in a model to update the display. You can do something like this but simpler to toggle display of nodes.

**Comment by raghulsekar** [comment]
@emminizer Thanks a lot, ill check
