### ISSUE TITLE
Information about .opt and .3db file formats?

### ISSUE THREAD

**Issue by dannagle** [USNavalResearchLaboratory/simdissdk#20]
I was playing with SIMDIS model editor, and I saw it saves in opt. I've never seen that file format. Is there a specification for it?

I also saw some "3db" models. I thought those may be an sqlite 3 db, but I did not have much luck there either. 

Thanks.

**Comment by emminizer** [comment]
OPT is a proprietary model format for the SIMDIS tool.  It has been superseded by 3DB.  Due to licensing restrictions on the models distributed with SIMDIS, we are unable to provide a tool to convert out of OPT, sorry.

**Comment by dannagle** [comment]
Does 3db have the same restrictions (proprietary,  license restrictions, unable to convert)?

**Comment by emminizer** [comment]
Yes, sorry.  The files that we distribute with SIMDIS have a license that only enable them to be used in the SIMDIS software toolkit.

**Comment by dannagle** [comment]
May I read the license for the models? Is it posted somewhere?

The only license I found is this one:
https://simdis.nrl.navy.mil/License.aspx

Thanks for your help and neat tool.
