### ISSUE TITLE
not realy an issue, but data source

### ISSUE THREAD

**Issue by ssnakus** [USNavalResearchLaboratory/simdissdk#22]
hi everyone,
i installed the simdis sdk, it works fine... just wondering if the simple data can be found somewhere?
cordially Brahim.

**Comment by emminizer** [comment]
Hi Brahim,

Thanks for your interest in the SDK.  The SDK is an infrastructure for building 3D visualization applications that run like the SIMDIS Toolkit.  We provide the infrastructure for displaying the data, but do not provide simulations of real data.  We do include some simple examples of how to get data into the SDK, included in the Examples directory.

You can download some data files from the SIMDIS_SDK-Data repository at https://simdis.nrl.navy.mil/SDK_1.8.aspx (for the 1.8 release) after logging into the SIMDIS site.  But Id on't think this is exactly what you're looking for.

If you download and install SIMDIS itself, it comes with several example ASI files.  Some of those can be loaded using the ASI Viewer example in the SDK.  Note that not all (or even most) features of ASI are supported in that parser; that example is a simplified parser for use in the SDK with simple examples.

Hope this helps.

 - Dan
