### ISSUE TITLE
Good gidelines / examples for creating plugins

### ISSUE THREAD

**Issue by SteveStrong** [USNavalResearchLaboratory/simdissdk#44]
Hello,  I have written a C++ program that integrates with SimDis by exporting a file in the ASI format.   Are there guidelines/examples that will let me embed this solution as a plugin.

**Comment by emminizer** [comment]
Hi Steve,

This is the project for the SIMDIS SDK, which is a C++ toolkit that is what the SIMDIS application is built upon.  This project is useful in particular for understanding how SIMDIS works, or for creating your own SIMDIS-like applications.  It also has general purpose utilities that can be used in your own applications and plug-ins.

It sounds like you're looking for the SIMDIS Plug-in API, which is distributed on the SIMDIS website along with every major SIMDIS release.  You can get the latest by logging in to https://simdis.nrl.navy.mil (an account is required), and select Download under the left menu.  The direct link to the current most recent version is https://simdis.nrl.navy.mil/10.0_SR4.aspx -- select your development / SIMDIS platform, then click the Plug-in API Distribution link.

The SIMDIS Plug-in API is separate from the SIMDIS SDK.  The Plug-in API includes examples for writing SIMDIS Plug-ins.  Help for the SIMDIS Plug-in API is provided on the SIMDIS Help Desk at https://simdis.nrl.navy.mil/jira/.  Thanks.

 - Dan
