### ISSUE TITLE
when use Triton in simQt ,the ocean surface will not animating. 

### ISSUE THREAD

**Issue by qiup-Q** [USNavalResearchLaboratory/simdissdk#54]
move Exmaples Ocean code into Qt , will find it.

**Comment by emminizer** [comment]
I apologize for the delay on answering this, I didn't get any email notification that I can find on this issue.

Please ensure you have Triton correctly configured.  You'll have to have osgEarth built with Triton support, and you will need to make sure that Triton gets found correctly on your system -- both the DLLs (or SO files) and the data directory.  You can use the environment variable TRITON_PATH to help.

**Comment by emminizer** [comment]
Unable to reproduce.  If you can provide more details about what you're seeing, whether you have error messages, and whether you've correctly set up the Triton path, I can take a look.
