### ISSUE TITLE
The compressed file(SIMDIS_SDK-Data.zip) is damaged

### ISSUE THREAD

**Issue by PLCreed** [USNavalResearchLaboratory/simdissdk#56]
When I tried to download the file SIMDIS_SDK-Data.zip three times and extract it, I was prompted for file corruption.

Is this the file you uploaded damaged?

**Comment by emminizer** [comment]
Thanks for your report.  I agree, I was having a hard time downloading it too.  I deleted it from the distro and re-uploaded the one from the SIMDIS site, which appears to download OK.

**Comment by nebsar** [comment]
Hi Daniel. How can I download SIMDIS_SDK-Data.zip?

**Comment by emminizer** [comment]
The data package is on the Releases page, e.g. https://github.com/USNavalResearchLaboratory/simdissdk/releases.

**Comment by nebsar** [comment]
Thank you, Daniel.

**Comment by nebsar** [comment]
Daniel, I have a question. The last version of osgEarth with is 3.3, is now built with GL3 support and does not support fixed functions and Materials etc... Does SIMDIS support the latest version of osgEarth, as well?

**Comment by emminizer** [comment]
Yes. We have a requirement to run on certain hardware and environments, including virtual machines, that requires the ability to run in OpenGL 3 Core Profile.. Some of these systems don't do well with GL2 fixed function pipeline with the Compatibility Profile. All of our testing and development is with GL3 in Core Profile.

**Comment by nebsar** [comment]
Thanks Dan.
