### ISSUE TITLE
Does DCS API work?

### ISSUE THREAD

**Issue by abduramann** [USNavalResearchLaboratory/simdissdk#69]
Hello,

In the website, it is written that DCS API has been deprecated since 2008. Today I've downloaded DCS examples and compiled them. They work well with SIMDIS application. Does this mean that DCSI API works but not supported, or it seems working but may work incorrectly?

Specifically, I want to show some scenarios using live mode but the existing Plugin-API requires two tasks: writing a plugin and writing another app to provide the plugin data. Well, I can do all of them in the plugin code but I'm not good at C++. I will use C#. That's why I'm asking. 

Thanks.

**Comment by emminizer** [comment]
Hello, questions like this are best fielded on the SIMDIS Help Desk at https://simdis.nrl.navy.mil/jira.  This is for the SIMDIS SDK project, which is unrelated to DCS, which was a networking API built on top of SIMDIS.

There is still a DCS Plug-in distributed with SIMDIS.  It is distributed but not supported or updated.  Examples may not work correctly.

The SIMDIS Plug-in API supports both C++ and Python plug-ins, as of SIMDIS 10.0 (SR8).  There are some examples in the Plug-in API distribution of both.  You do not necessarily need to write a separate application to feed data to SIMDIS unless you're planning on a centralized distribution to multiple SIMDISes.  If you do, you can write that other application in whatever format you like and create your own network protocol to communicate to the plug-in.  If you're just generating data, you can do it internal to the plug-in like in the Simple Server example.

If you have further questions about DCS or the Plug-in API, please raise them on the SIMDIS Help Desk.  Thanks,

 - Dan
