### ISSUE TITLE
The osg particle effect is not displayed

### ISSUE THREAD

**Issue by yuxiangyu** [USNavalResearchLaboratory/simdissdk#74]
When we used simdissdk , we suddenly found that the paricle system used in osg/osgearth application can not work.  Can someone tell me the reason?

**Comment by emminizer** [comment]
Do you have sample code or more details? There is not enough information to give any suggestions here. We do not use the particle system regularly and there's no known incompatibilities.

I was under the impression that osgParticle was all but deprecated, quite old and using older, slower methods for particle display. The OSG binaries in our third party pack are built with core profile enabled for maximum support on e.g. VMs; it's possible there could be some conflict there between osgParticle and core profile if that's the case.

**Comment by yuxiangyu** [comment]
just a simple fireEffect as: osg::ref_ptr<osgParticle::FireEffect> fe = new osgParticle::FireEffect(postion,100.0,100.0); In the osgEarth application it can be displayed as 
![image](https://user-images.githubusercontent.com/965278/132150039-927cd97c-2ff0-47c5-9ec9-16d539d2832d.png)
but in the simdissdk application , it did not show any effect

**Comment by emminizer** [comment]
Best guesses:
* Some kind of depth issue with Logarithmic Depth Buffer, which defaults on for SDK.
* Missing a call to osgEarth::Registry::shaderGenerator().run(). Looks like there's a texture here, and that won't display without the shader generator.

I'm not familiar with osgParticle, and we don't use it. My only real experience is from issues like https://github.com/openscenegraph/OpenSceneGraph/pull/900#issuecomment-576212703 where Robert states:

> doing particle systems on the CPU is pretty daft these day so I really consider osgParticle really just there for backwards compatibility so don't see it as something we should invest time in trying to perfect and risk breaking when users really should be implementing particle systems on the GPU on modern hardware

This is part of why we have not investigated osgParticle. However if there's some change on our end that you see that can help, we're interested to hear. Thanks!

 - Dan

**Comment by yuxiangyu** [comment]
Thanks a lot for your proposal.

**Comment by yuxiangyu** [comment]
Maybe I  have found the key of the problem that the particles effect generated by osg can only be added child under the root node for an unknown reason like that:
osg::ref_ptr<osg::MatrixTransform> trans = new osg::MatrixTransform;
...
osg::ref_ptr<osgParticle::PrecipitationEffect> pe = new osgParticle::PrecipitationEffect;
...
 trans->addChild(pe);
 viewer->getMainView()->getSceneData()->asGroup()->addChild(trans);

**Comment by emminizer** [comment]
Thank you for sharing the possible workaround. That seems less convenient than adding as a child in the proper location in the scene, but at least seems workable.
