### ISSUE TITLE
Qt6 Support

### ISSUE THREAD

**Issue by jhoweparsons** [USNavalResearchLaboratory/simdissdk#78]
I need to talk with someone about what plans (if any) the SIMDIS SDK has for migration to Qt6.

**Comment by emminizer** [comment]
At this point we do not have plans to migrate to Qt6 internally. The licensing changes have been a little concerning, and we've encountered significant issues in the software especially with regards to ``QDockWidget`` past Qt 5.9.

We would welcome patches that enabled Qt6 support as long as they did not break Qt5 support.
