### ISSUE TITLE
Flight Track History Display

### ISSUE THREAD

**Issue by kinsung** [USNavalResearchLaboratory/simdissdk#79]
Simdissdk is a powerful toolkit. How to set the flight track prefs, so it can display effect like tacview's tracker?

https://d2.alternativeto.net/dist/s/tacview_979525_full.jpg?format=jpg&width=1600&height=1600&mode=min&upscale=false

**Comment by emminizer** [comment]
We currently don't support exactly that display out of the box. If you set track prefs to bridge mode ``TrackPrefs.Mode.BRIDGE``, you'll get the vertical lines. If you set it to ribbon mode ``TrackPrefs.Mode.RIBBON``, you'll get a non-filled outline showing the orientation vector along the history trail, as shown in the picture. We do not have a combined mode showing both at the same time.

You could get somewhat close by turning on ribbon mode then turning on the ``TrackPrefs.altMode`` flag to drop a line from current position to the ground.

**Comment by kinsung** [comment]
Thanks for your reply.
Track History ribbon mode （TrackPrefs.Mode.RIBBON） display Non-filled outline ribbon, it doesn't look as good as tacview's silk textured ribbon.

**Comment by emminizer** [comment]
Thank you for the suggestion. The downside of the silk textured ribbon is going to be performance and complexity, especially in larger scenarios with thousands of entities. We're not opposed to such a functionality but we are not sponsored to implement it. You are welcome to enhance and submit the feature as A PR however.

**Comment by kinsung** [comment]
I agree with you. Maybe I can try it sometime.
