### ISSUE TITLE
osgeo::proj::io::FactoryException?

### ISSUE THREAD

**Issue by yuxiangyu** [USNavalResearchLaboratory/simdissdk#87]
When runs the newest version of the simdissdk examples with qt (for example TestViewManager) , the application will print the osgeo::proj::io::FactoryException in the visual studio output console (for example vs2019). Is it a bug?

**Comment by emminizer** [comment]
Hello! I have not seen this error before. This is not code that we use directly, so this is an issue with third party libraries. It looks to be a problem with your Proj library. You might need to set the PROJ_LIB environment variable to your Proj's data/proj directory.

**Comment by yuxiangyu** [comment]
Thank you, it does not affect any program operation just print the sentence. I have found which caused it is the map init function in the osgearth3.2. So it explains the simdisssdk 1.14 does not cause the issue。
